### ISSUE TITLE
28146 Killed  

### ISSUE THREAD

**Issue by yywyaoyaowu** [noble-research-institute/TDNAscan#6]
Hi,
I'm Yaoyao Wu, and I'm using your TDNAscan to detect if there's TDNA insert. I use the example test, it works. When use my data, it says "sh: line 1: 28146 Killed " , below is the detail error. Have you met this before. Thank you!

sh: line 1: 28146 Killed                  bwa mem -T 20 -t 8 ./zhihong_tdna_Nb2EHA105/pKTFNb2.fasta zhihong/zhihong_tdna_Nb2EHA105_1.fq zhihong/zhihong_tdna_Nb2EHA105_2.fq > ./zhihong_tdna_Nb2EHA105/1.TDNA.sam
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] parse error at line 48797202
[main_samview] truncated file.
[bam_sort_core] merging from 40 files...
Running the step2: capture all informative reads from SAM file from Step1 
Splitting /vol3/agis/huangsanwen_group/wuyaoyao/tpomato.group/zhihong/TDNAscan-master/./zhihong_tdna_Nb2EHA105/tmp/1.TDNA.sam into multiple files with 10000 lines

Created 4881 files.
parallel Processing
Time for multiple processes: 93.2002949715secs

**Comment by yywyaoyaowu** [comment]
BTW, I have got 1.TDNA_sort.bam; 2.informative_genome_r1.fq

**Comment by yinbingge** [comment]
Hello Yaoyao,

Thank you for your feedback. Can I ask if you used the same version  of software or Linux system as we mentioned in TDNAscan github?

Thanks

Yinbing

**Comment by yywyaoyaowu** [comment]
Thank you! I change the samtools in to 1.3 version python 2.7 and bwa is 0.7.5a-r405.  And the example data works. But I met another error '[gzclose] buffer error
[bwa_index] Pack FASTA... [bns_fasta2bntseq] Failed to allocate 0 bytes at bntseq.c line 270: Success
[E::bwa_idx_load] fail to locate the index files'.

**Comment by yywyaoyaowu** [comment]
BTW. our linux system is centos6.5. Is this cause the problem?

**Comment by sunliang3361** [comment]
Hi Yaoyao,
Did you trim your reads before running tdnascan? We would recommend you to trim your NGS reads before using our tools. It looks like your sequence quality is not that good. You can try NGS trimmer such as trimmomatic.

Best,
Liang

**Comment by yywyaoyaowu** [comment]
Thank you! I will trimmed the reads then run tdnascan.py.
