### ISSUE TITLE
File write failed (wrong size); writing to standard output failed

### ISSUE THREAD

**Issue by yywyaoyaowu** [noble-research-institute/TDNAscan#7]
Hi,
I trimmed the reads as you sugessted, but I still got error. And I checked bwa and samtools works, but still got error. And "parallel Processing" is running for several days.

[main] CMD: bwa mem -T 20 -t 8 ./zhihong_tdna_Nb2Omega_trim_ssamtools/pKTFNb2.fa zhihong_tdna_Nb2Omega_trim_1.fq zhihong_tdna_Nb2Omega_trim_2.fq
[main] Real time: 2245.428 sec; CPU: 18272.760 sec
[E::bgzf_flush] hwrite error (wrong size)
[bam_sort_core] failed to create temporary file "./zhihong_tdna_Nb2Omega_trim_ssamtools/1.TDNA_sort.bam.tmp.0015.bam": Bad address
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
[E::hts_open_format] fail to open file './zhihong_tdna_Nb2Omega_trim_ssamtools/1.TDNA_sort.bam'
samtools index: failed to open "./zhihong_tdna_Nb2Omega_trim_ssamtools/1.TDNA_sort.bam": No such file or directory
Splitting /local/workdir/yw2326/TDNAscan/./zhihong_tdna_Nb2Omega_trim_ssamtools/tmp/1.TDNA.sam into multiple files with 10000 lines
Created 33299 files.
Running the step1: map all reads to T-DNA sequence to generate a SAM file 
Running the step2: capture all informative reads from SAM file from Step1 
parallel Processing

**Comment by yywyaoyaowu** [comment]
BTW, the python is 'Python 2.7.15' and samtools is 1.3.1.

**Comment by sunliang3361** [comment]
Hi Yao,
Could you attach your log file? I cannot see the error messages from what you shared. Thank you
